services:
  php:
    image: moodlehq/moodle-php-apache:7.4
    ports:
      - "8100:80"
    volumes:
      - ./moodle:/var/www/html
      - moodledata:/var/www/moodledata
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: moodle
      MARIADB_PASSWORD: moodle
      MARIADB_DATABASE: moodle
      MARIADB_USER: moodle
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
volumes:
  moodledata: {}
