services:
  php:
    image: moodlehq/moodle-php-apache:7.4
    ports:
      - "8100:80"
    volumes:
      - ./moodle:/var/www/html
      - moodledata:/var/www/moodledata
  db:
    image: mariadb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      MARIADB_ROOT_PASSWORD: moodle
      MARIADB_PASSWORD: moodle
      MARIADB_DATABASE: moodle
      MARIADB_USER: moodle
volumes:
  moodledata: {}
