services:
  php:
    image: moodlehq/moodle-php-apache:7.4
    ports:
      - "8100:80"
    volumes:
      - ./moodle:/var/www/html
      - moodledata:/var/www/moodledata
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: moodle
      MYSQL_PASSWORD: moodle
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
    volumes:
      - db-storage:/var/lib/mysql
volumes:
  db-storage: {}
  moodledata: {}
